# Generated by Django 5.2.7 on 2025-10-08 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0003_alter_pokemon_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonentity',
            name='Appeared_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 8, 12, 37, 35, 193623, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='Disappeared_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 8, 12, 37, 35, 208419, tzinfo=datetime.timezone.utc)),
        ),
    ]
