# Generated by Django 5.2.7 on 2025-10-08 13:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0006_alter_pokemonentity_appeared_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonentity',
            name='Appeared_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 8, 13, 26, 28, 968284, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='Disappeared_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 8, 13, 26, 28, 983356, tzinfo=datetime.timezone.utc)),
        ),
    ]
