# Generated by Django 5.2.7 on 2025-10-08 13:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0005_remove_pokemon_title_pokemon_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonentity',
            name='Appeared_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 8, 13, 25, 49, 124715, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='Disappeared_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 8, 13, 25, 49, 139808, tzinfo=datetime.timezone.utc)),
        ),
    ]
