# Generated by Django 5.2.7 on 2025-10-08 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0012_alter_pokemon_description_alter_pokemon_title_jp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='Appeared_at',
            new_name='appeared_at',
        ),
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='Disappeared_at',
            new_name='disappeared_at',
        ),
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='Lat',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='Lon',
            new_name='lon',
        ),
        migrations.RemoveField(
            model_name='pokemonentity',
            name='Defence',
        ),
        migrations.RemoveField(
            model_name='pokemonentity',
            name='Health',
        ),
        migrations.RemoveField(
            model_name='pokemonentity',
            name='Level',
        ),
        migrations.RemoveField(
            model_name='pokemonentity',
            name='Pokemon',
        ),
        migrations.RemoveField(
            model_name='pokemonentity',
            name='Stamina',
        ),
        migrations.RemoveField(
            model_name='pokemonentity',
            name='Strength',
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='title_jp',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название на японском'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='title_ru',
            field=models.CharField(max_length=200, verbose_name='Название на русском'),
        ),
        migrations.AddField(
            model_name='pokemonentity',
            name='defence',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Защита'),
        ),
        migrations.AddField(
            model_name='pokemonentity',
            name='health',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Здоровье'),
        ),
        migrations.AddField(
            model_name='pokemonentity',
            name='level',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Уровень'),
        ),
        migrations.AddField(
            model_name='pokemonentity',
            name='pokemon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pokemon_set', to='pokemon_entities.pokemon', verbose_name='Покемон'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pokemonentity',
            name='stamina',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Выносливость'),
        ),
        migrations.AddField(
            model_name='pokemonentity',
            name='strength',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Сила'),
        ),
    ]
